auth_key = "AIzaSyC8kG6ZWPh0XwEX5Z-X6K0MmxPL8wrr1Ys"

auth_key2 = "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"